### ISSUE TITLE
Generalize Ability system

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#115]
in its current state, the ability system is limited to Creatures. This also means that Effects, AttributeModifiers etc. can only be triggered by Creatures. However, it could be desirable to have Emitters, for example, that apply a burn effect etc...
Also, the Ability framework is rather genre specific. We should think about pulling parts of it out the engine.

**Comment by dknz2008** [comment]
Great idea! 
What do you mean by genre specific and pulling parts of it out of the engine? Are you referring to functionality that many game genres might not have and therefore the engine should not try to handle (instead be more general)?

**Comment by gurkenlabs** [comment]
The general idea behind this is pretty much how you described it: make the engine more general and modular while still providing the functionality for the developer if he wants to use it.

The ability system is just one example of this general idea of keeping the engine to the core functionality and providing additional components for more specific (e.g. genre specific) functionality.

The other topic of this issue is to recfactor and properly seperate the current implementation so that it will be even possible to provide it as seperate module.

**Comment by nightm4re94** [comment]
I've been thinking about this a bit more and maybe we could extend this system so the Effect is basically only a target selector. Once the targets are selected, something like a `Condition` could be applied to an `IEntity` directly without any knowledge of its origin. Of course, one could initialize such a condition with the attributes of an Ability, but it could also be more static and not tied to Abilities or combat. I'm thinking of examples like environmental hazards, e.g. poison pits, flamethrowers, or ice fields.
