### ISSUE TITLE
A request for edit access

### ISSUE THREAD

**Issue by TheRamenChef** [gurkenlabs/litiengine#164]
I've made a number of contributions to the engine through pull requests, and they're rather inconvenient to make, because I'm constantly having to merge with the main repository. For this reason I am requesting direct edit access to the main repository. This would allow me to make minor edits much faster.

I still plan on putting more significant edits that might not be approved into pull requests, and if you don't like a change I made, you can always roll it back.

**Comment by steffen-wilke** [comment]
I do understand that request. For minor, obvious fixes, it's often times simpler to just commit and push.

In general I think that nothing speaks againt this since you've already contributed numerous solid changes and improvements to the engine.

While it's true that it would always be possible to rollback a commit, I think that this would be a situation that we all need to avoid since it just leads to unnecessary work and discussion.
So if there are any doubts about a commit/change, feel free to discuss the topics with us beforehand or just open a pull request as you already suggested.

As we move forward with the development of the LITIengine, we try to establish the habit of implementing larger chunks of features using pull requests from feature branches ourselves.

We're currently restructuring our repository and will introduce a **dev** branch that will be merged to the **master** whenever we build a new version.
It will be permitted to force push to the **master** branch and all development will take place in the **dev** branch (or feature branches).

As soon as we've done that, we'll grant you push access to repository.
Looking forward to our future collaboration!

**Comment by TheRamenChef** [comment]
Any progress on this? I can see the `dev` branch, but it doesn't appear to be in use.

**Comment by steffen-wilke** [comment]
We've decided to postpone the restructuring of the repository with the `dev` branch until the first official release 1.0. For now, we'll still use the "old" workflow. I've added you to the list of Collaborators for this project now, so you can directly push to the `master` branch.

For larger changes or something that might be a topic of discussion, please keep on using PRs or open an issue first before pushing the changes.

Looking forward to your future contributions 👍
