### ISSUE TITLE
Utiliti crashes

### ISSUE THREAD

**Issue by bartzzdev** [gurkenlabs/litiengine#178]
Hey, I've written a comment on your YouTube channel about my problem with Utiliti.
![image](https://user-images.githubusercontent.com/16993922/46430659-00385800-c74a-11e8-914b-d214e5ce09d3.png)

And yeah, firstly I want to tell you that my problem is not just at the latest version of Utiliti. I tried to run this from different versions and the result was the same with one small difference.
At the latest, there's an exception thrown to _crash.txt_.
![image](https://user-images.githubusercontent.com/16993922/46430854-86ed3500-c74a-11e8-91c3-547ec4cd0ea9.png)

I don't know if they are some special things to make it working, maybe I just missed something.

**Comment by TheRamenChef** [comment]
Are the main LITIEngine classes on the classpath?

**Comment by steffen-wilke** [comment]
What java version are you using?
This issue seems to me like you have Java 9 or 10 installed or even OpenJDK (might be related to #162).
Oracle has dropped the JAXB library in the newer Java versions and we yet need to make the LITIengie compatible. Unfortunately, there is no backward compatibility on this.

**Comment by bartzzdev** [comment]
You're right. I have changed my Java version already and it seems to be working. Thanks!
