### ISSUE TITLE
Use thread-safe lists instead of CopyOnWriteArrayLists

### ISSUE THREAD

**Issue by edgelord314** [gurkenlabs/litiengine#187]
In this project, I saw many CopyOnWriteArrayLists, which I think are used due to concurrent exceptions. But these can get slow, and so I would rather use `Collections.getSynchronizedList(new ArrayList<>)`. If you do so, you can't use iterators (and no `for` loop).

**Comment by steffen-wilke** [comment]
Thank's for the hint. 

I think we should have to look at this depending on the usage. While it's true that there are some usages of the `CopyOnWriteArrayList` that might be replaced by `Collections.getSynchronizedList(new ArrayList<>)` in order to save some performance, such improvements should have some kind of goal, especially when they come with the downside of potential `ConcurrentModificationExceptions` or a different handling of the collection.

I've done a lot of performance profiling with the LITIengine and the `CopyOnWriteArrayLists` are on the far end when it comes to potential candidates for improving the performance.

In fact, almost all of the CPU time is spent by actual rendering processes on the `Graphics2D` instance (either images or shapes).

Nevertheless, I don't deny that we might be able to squeeze out a few more frames when optimizing all these occurences.

**Comment by edgelord314** [comment]
In my java2d engine, rendering is actually not the problem, but all the calculations. And also, rendering images should be faster than rendering primitives, thats why Salty Engine tries to render created images instead of rendering primitives.

**Comment by steffen-wilke** [comment]
We've evaluated which `CopyOnWriteArrayLists` to replace and actually found some places where a synchronized list yielded a better performance. Thank's for the hint.
