### ISSUE TITLE
Update sprites and maps when opening utiLITI

### ISSUE THREAD

**Issue by CalvinMT** [gurkenlabs/litiengine#227]
If changes were made to the sprites, opening the utiLITI will show the old sprites and there is no fast way to update them.
Currently, you need to go and fetch your Spritefile to re-import it.

What would be good is to have an update function running when the utiLITI opens-up, but also to have the possibility to reload while the utiLITI is already open (e.g. F5 refresh in a browser).

**Comment by CalvinMT** [comment]
Could be good if maps were updated in the same way.
Probably better with a prompt message that would ask you to choose (e.g. by ticking boxes) which elements you would want to update.

**Comment by nightm4re94** [comment]
I agree that it would be pleasant to update selected resources without having to re-import them. 
I'll see what I can do for you, my friend.

**Comment by nightm4re94** [comment]
I might have come up with something today. I'll let you know how successful it was 😅

**Comment by CalvinMT** [comment]
@nightm4re94
I forgot to specify a reason, which is that one would not have to replace every elements (Props, Creatures, Lights, Triggers, etc...) at the same place when updating/refreshing maps.

**Comment by nightm4re94** [comment]
As you might have guessed from commit e4b97786f7421774fbcef369e9706dece8007e90, we are not going to implement this in LITIengine's current state. As mentioned in my other comment, the "single game resource file" approach makes it tedious and kind of hacky to add file references to all resources.
We've had a discussion about asset management in general and have come to the conclusion that we will not fundamentally change our approach before the v1.0 release of LITIengine. In the long run, we absolutely intend to back away from it by working on resource files directly instead of storing them in one large file. LITIengine has seen a ton of different variations of asset management so far, but we are now convinced that it is more intuitive to not have a single game resource file.
