### ISSUE TITLE
New TMX overhaul breaks the ambient light sources

### ISSUE THREAD

**Issue by TheRamenChef** [gurkenlabs/litiengine#233]
From @nightm4re94, commenting on #232:

> Thank you a lot, these are some great improvements!
However, I've noticed after merging the branch that the AmbientLight is not working for any of the Map orientations anymore (While there were bugs with hexagonal maps, at least it had been working for orthogonal maps previously). Please fix this as soon as possible.

Looking at the code more closely, is there any reason it can't *assume* an orthogonal orientation? It’s split into tiles as bite-sized pieces to render, but it doesn't appear to have any meaningful connections to tiles.

**Comment by steffen-wilke** [comment]
In general, I'd say that the `AmbientLight` layer doesn't necessarily have to reflect the map orientation. In fact, the lighting system in the engine is not really related to tiles but to pixel precise lights and shadows. The current segregation was introduced in order to make it possible to update a certain region of the light layer without the need to recalculate the entire layer. Originally, the engine only supported orthogonal orientation which is why this concept was closely bound to it.

@TheRamenChef I think in theory it should be possible to to leave the segregation algorithm as currently implemented. It might be necessary though to project the region that needs to be updated depending on the orientation. Currently, an orthogonal `Rectangle2D` is used to determine the region (see usages of `ColorLayer.updateSection(Rectangle2D rectangle)`).

**Comment by nightm4re94** [comment]
![lights](https://user-images.githubusercontent.com/26114385/53914142-3e210b80-405d-11e9-9831-2826aab81d69.png)
This is the current state of our Ambient Lighting and Light Sources. Oddly, hexagonal maps now actually seem to be the only orientation with working lighting (except that only the ColorLayer Tiles intersecting a LightSource are rendered right away when reloading a map.
Our orthogonal test map couldn't even be loaded anymore due to an error arising in the `ColorLayer.setTiles()`-method: In line 122, the code `final BufferedImage smallImage = img.getSubimage(subX, subY, map.getTileWidth(), map.getTileHeight());` yields the following: `java.awt.image.RasterFormatException: y lies outside raster`

**Comment by TheRamenChef** [comment]
Now that I think about it, there's actually no reason to break it apart into separate images. The Java graphics system is optimized; it *knows* that it only needs a part of the image.

Also, would you be able to send me a sample program for the light sources? I don't use `AmbientLight`, so I don't know how it's supposed to behave.

**Comment by steffen-wilke** [comment]
It is necessary for partially updating the ambient light instead of having to reassemble the entire image for the map.
This has been introduced to allow `LightSources` to be enabled/disabled or moved during runtime without to much of a performance loss.

**Comment by TheRamenChef** [comment]
Alright, I've created a `fix-light` branch that contains what is hopefully a fix. Can you check it out?

Also, it is possible to partially update an image; it's done in the branch.

**Comment by steffen-wilke** [comment]
> Also, it is possible to partially update an image; it's done in the branch.

Ah okay, so that's a cleaner approach to do things, assuming the update performance is similar to the old approach (didn't do any profiling yet).

I've done a quick test with the branch with a bright ambient light set and there still seems to be an issue with the new approach when updating lights:
![ambient-light](https://user-images.githubusercontent.com/7015370/54051137-5ae64c00-41e1-11e9-8ca3-86d4216e0049.gif)

**Comment by TheRamenChef** [comment]
Is it working now?

**Comment by steffen-wilke** [comment]
I think it updates the correct areas now but something is off with the `AlphaComposite` now. I think this is due to your changes in the `AmbientLight` class with commit 9a8186a0023ceab6cfab95ade8d39b65bba7aaad.
![ambient-light-2](https://user-images.githubusercontent.com/7015370/54083799-e1597580-4328-11e9-820b-701c56f6ed5b.gif)

**Comment by TheRamenChef** [comment]
Does it work without that commit? I'm perfectly fine with it being reset.

**Comment by steffen-wilke** [comment]
Sadly, it doesn't. Reverting only that commit doesn't render the AmbientLight at all and only renders the lights. Trying to only revert the changes on the `AmbientLight` class yielded the same visual result as reverting the entire commit: `LightSources` are rendered properly but the `AmbientLight` isn't rendered at all.

![ambient-light-3](https://user-images.githubusercontent.com/7015370/54090130-24d7d200-4371-11e9-83a8-19e5b661c88b.gif)

**Comment by TheRamenChef** [comment]
At this point, I have no idea what's causing the issue and I didn't even touch it with my pull request. Could you please send me a sample program to test the ambient light? And maybe the intended behavior as well?

**Comment by steffen-wilke** [comment]
commit fd3930d952ba0addd9a9392543c6d4c0b2cf36eb should fix this now
