### ISSUE TITLE
utiLITI: bug in properties if 'Enter' isn't pressed

### ISSUE THREAD

**Issue by CalvinMT** [gurkenlabs/litiengine#253]
There's a bug where if you start changing the name or the value of a property, but don't validate it by pressing 'Enter', the changes made won't take place but will show up in the properties of other objects until the changes are validated (pressing 'Enter').

I find it hard to explain, so here's an example to replicate it:
- Create two objects in which you create at lest one property for each (doesn't have to have the same name).
- Select one of the objects created and start changing the name or the value of its property.
But _**don't**_ press 'Enter' once finished.
- Select the other object and look at its properties. You should now be able to see the problem.

I personnaly think that the changes should be saved when the user doesn't press 'Enter', but clicks somewhere else instead. Just like when the name of an object is changed.

**Comment by steffen-wilke** [comment]
@CalvinMT Thank's for reporting this. The issue itself should be fixed with the next release of the editor.

> I personnaly think that the changes should be saved when the user doesn't press 'Enter', but clicks somewhere else instead. Just like when the name of an object is changed.

While I would agree in general, handling input in a table provides enhanced user experience (e.g. support for ESCAPE, ENTER, TAB, ...) and changing its default behavior would be a bigger change to the current implementation, so we'll keep the necessity to confirm a change with ENTER or TAB for the time being.
