### ISSUE TITLE
Fix Reassigning map IDs.

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#299]
Reassigning Map IDs doesn't seem to do anything in utiLITI currently.

**Comment by YannikSchoeberl** [comment]
I just debugged this and found the following: in MapMenu.java, there's this snippet:
```
try {
        String min = JOptionPane.showInputDialog(Resources.strings().get("panel_reassignMapIds"), 1);
        if (min == null || min.isEmpty()) {
          return;
        }

        int minID = Integer.parseInt(min);
        Editor.instance().getMapComponent().reassignIds(UI.getMapController().getCurrentMap(), minID);
      } catch (Exception e) {
        log.log(Level.SEVERE, "No parseable Integer found upon reading the min Map ID input. Try again.");
      }
```
I found that the call 
```
UI.getMapController().getCurrentMap()
```
which is used as the first parameter in the reassignIds method, always returns null. Therefore it's simple logic that the reassigning doesn't do anything because the reassignIds method throws a NullPointerException which is caught and that's it.
