### ISSUE TITLE
[Security] ClientConnection ids are sequential

### ISSUE THREAD

**Issue by Gamebuster19901** [gurkenlabs/litiengine#360]
**Describe the bug**
The client IDs in ClientConnection are sequential. This means an attacker will know that the first player to join the game has a client id of 1, the second has 2, etc. This (currently) allows an attacker to easily guess another player's id and pretend to be them.

https://github.com/gurkenlabs/litiengine/blob/649ceeacc6c164314cfc900ad734ebda0bd5ba12/src/de/gurkenlabs/litiengine/net/server/ClientConnection.java#L41-L48

**Expected behavior**
Client connections should be stored using a random value. I recommend using java.util.UUID.randomUUID(); Also add a note to the field to and tell developers do not accidentally expose the value to connected clients.

**Your System:**
 - LITIENGINE version: [e.g. 0.5.0-beta]

**Comment by steffen-wilke** [comment]
**Bigger picture:**

The whole `net` package is probably one of the oldest parts of the engine which has not been actively used/maintained for years. We've actually discussed removing this code from the engine for the 1.0 release because there is so much more that goes into a proper networking library. The current state is a very rudimentary implementation.

Nonetheless, I think these security suggestions by themselves do make sense, so thank you for tracking them.
