### ISSUE TITLE
Several Exceptions Unhandeled 

### ISSUE THREAD

**Issue by eHag-FRU** [gurkenlabs/litiengine#402]
**Describe the bug**
There are several crashes in the utiLITI-v0.5.1 beta. 

**Stack Trace**
The error message you get either in your console or the `crash.txt` located in your program's root directory.

```
Thu May 13 22:45:14 EDT 2021 Main Update Loop threw an exception:
java.lang.NullPointerException
	at de.gurkenlabs.litiengine.graphics.RenderComponent.render(RenderComponent.java:120)
	at de.gurkenlabs.litiengine.GameLoop.process(GameLoop.java:92)
	at de.gurkenlabs.litiengine.UpdateLoop.run(UpdateLoop.java:57)
```

**To Reproduce**
1. Open a previous .liti file in utilLITI

**Expected behavior**
Opens the file and displays the map, as well as successful importation of tilesets.

**Screenshots**

**Your System:**
 - OS: Windows 10
 - LITIENGINE version: 0.5.1-beta
 - Java JDK/JRE version: JDK 14
 - Screen resolution: 1366 X 768

**Additional context**
Here is the log
[game.log](https://github.com/gurkenlabs/litiengine/files/6476198/game.log)
 from utiLITI

**Comment by Gamebuster19901** [comment]
Can you remove the code block on this issue and #401? Can't see attachments or images with it there.

**Comment by eHag-FRU** [comment]
> Can you remove the code block on this issue and #401? Can't see attachments or images with it there.

Yes, Give me one sec here

**Comment by nightm4re94** [comment]
This is not a general issue:
As the log says, there is a path to a non-existing tileset file in your map:
`Caused by: java.io.FileNotFoundException: C:\Users\Elliott Hager\eclipse-workspace\Tetris\Background Block.tsx (The system cannot find the file specified)`
To resolve this, open the .tmx map with a text editor and provide the correct path to the tileset there. (Paths without spacing are often more robust, by the way)
