### ISSUE TITLE
Update TileData specification

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#463]
[\<data\>](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#data)
compression: The compression used to compress the tile layer data. Tiled supports “gzip”, “zlib” and (as a compile-time option since Tiled 1.3) “zstd”.

**Comment by steffen-wilke** [comment]
While `zstd` is a good algorithm for compressing `TileData`, supporting it would lead to the LITIENGINE either adding an external dependency to libraries like https://github.com/airlift/aircompressor or https://github.com/luben/zstd-jni or providing an extension point for the compression/decompression during serialization.

Since there is not a big expected value for the projects that are usually realized with the engine,

⚠ **LITIENGINE will not support `zstd` compression for the time being and rely on `gzip` and `zlib` default java implementations instead.**
