### ISSUE TITLE
Help me please!

### ISSUE THREAD

**Issue by Documentalism** [gurkenlabs/litiengine#53]
Can i have a simple Game Example Shooting like Invaders code to know how to use the Lib.

**Comment by gurkenlabs** [comment]
Thank's for your interest, we're currently in a state of development where some parts of the engine are still subject to change and therefore we didn't create full sample projects yet. However, we're planning on releasing the source code of a jam game we did with the engine to the public so that the users at least might get an idea of how to use everything.

In the meantime, we'll refer you to an issue, where we've posted some sample code for a similar question.

Issue #34 

Hope you understand that everything is not quite set up yet.

**Comment by steffen-wilke** [comment]
We've started a tutorial series [HERE](https://litiengine.com/getting-started-setup-the-game-project/). This series is not done just yet but it will cover all required steps to set up and getting started with the LITIengine. Once we reach version 0.5.0-beta, well also provide more sample games for you to check out.
