### ISSUE TITLE
Delete tilesets and their sprites from gamedata file when deleting maps

### ISSUE THREAD

**Issue by nightm4re94** [gurkenlabs/litiengine#97]
.

**Comment by steffen-wilke** [comment]
I don't think we can do this in every case. A `TileSet` doesn't necessarily belong to a `Map` and it can in fact be reused by many maps.

Imagine the following:
1. You've added a tileset to your project. 
2. You add a map that's using it. 
3. You decide to remove the map again

I don't think that the tileset should be removed in this case and since we don't have any meta-data about how a tileset was imported (indirectly from a particular map or directly).

I'm going to closes this issue since I don't see the additional structs and logic to cover all use cases being worth the value of this.
